### ISSUE TITLE
Fixing Loading issues

### ISSUE THREAD

**Issue by dioscarr** [drodriguez16/dashbored#1]
# Loading not working properly
The App is loading duplicate version of the same item so the loading document mechanism needs to be cleaned up.

# Task
- [ ] Troubleshoot the the app to get an idea of the requence of events on the firebase subscription. 
- [ ] There are additional triggers happening on chaining database callback and firebase storage callback
- [ ] Handle the url update from from the Upload mechanish as oppose to query the firebase starage on the firebase database callback.
- [ ] Update the sequence of event when uploading a new file to resolve the url to download file before adding the file metadata to the database.
- [ ] Update File upload schema with two additional fields, `id` and `downloadUrl`
